=== CeeJay79/aion-emu-backup/trunk/AE-go_DataPack/gameserver/data/static_data/skills/skills.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:include schemaLocation="../import.xsd" />

	<xs:element name="skill_data" type="skillData" />

	<xs:complexType name="skillData">
		<xs:sequence>
			<xs:element ref="import" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="skill_template" type="SkillTemplate" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

  <xs:simpleType name="Element">
    <xs:restriction base="xs:string">
      <xs:enumeration value="NONE"/>
    	<xs:enumeration value="FIRE"/>
    	<xs:enumeration value="EARTH"/>
    	<xs:enumeration value="WIND"/>
    	<xs:enumeration value="WATER"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="Type">
    <xs:restriction base="xs:string">
    	<xs:enumeration value="DEFAULT"/>
    	<xs:enumeration value="SPELL_OBJECT"/>
    	<xs:enumeration value="SPELL_SIMPLE"/>
    	<xs:enumeration value="HEAL_OBJECT"/>
    	<xs:enumeration value="HEAL_SIMPLE"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="Probability">
		<xs:restriction base="xs:float">
			<xs:minInclusive value="0.0"/>
			<xs:maxInclusive value="100.0"/>
		</xs:restriction>
	</xs:simpleType>
		
	<xs:complexType name="SkillTemplate">
		<xs:attribute name="skill_id" type="SkillId" use="required" />
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="level" type="xs:int" use="required" />
		<xs:attribute name="skill_type" type="Type" default="DEFAULT" />
		<xs:attribute name="inflicts" type="xs:int" default="0" />
		<xs:attribute name="heals" type="xs:int" default="0" />
		<xs:attribute name="element" type="Element" default="NONE" />
		<xs:attribute name="cost" type="xs:int" default="0" />
		<xs:attribute name="probability" type="Probability" default="100.0" />
		<xs:attribute name="recharge_time" type="xs:int" default="0" />
		<xs:attribute name="launch_time" type="xs:int" default="0" />
		<xs:attribute name="target" type="skillTarget" default="TARGET" />
	</xs:complexType>
	
	<xs:simpleType name="skillTarget">
		<xs:restriction base="xs:string">
			<xs:enumeration value="TARGET" />
			<xs:enumeration value="TARGET_SELF" />
			<xs:enumeration value="SELF" />
			<xs:enumeration value="LOCATION" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="skillId">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="60000"/>
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== CeeJay79/aion-emu-backup/trunk/AE-go_DataPack/gameserver/data/static_data/skills/skill_templates.xml
<?xml version="1.0" encoding="UTF-8"?>
<skill_data  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="skills.xsd">
	<skill_template skill_id="1801" name="Return" level="1" recharge_time="1200" launch_time="6" />
	<skill_template skill_id="1803" name="Bandage Heal" level="1" recharge_time="16" launch_time="4" heals="178" skill_type="HEAL_OBJECT">
		<needs item="169300001" quantity="1" />
	</skill_template>
	<skill_template skill_id="1351" name="Flame Bolt I" level="1" element="FIRE" cost="40" recharge_time="1" launch_time="2" inflicts="80" skill_type="SPELL_SIMPLE" />
	<skill_template skill_id="975" name="Smite I" level="1" element="EARTH" cost="18" recharge_time="2" launch_time="2" inflicts="81" skill_type="SPELL_SIMPLE" />
	<skill_template skill_id="169" name="Severe Strike I" level="1" launch_time="1" recharge_time="10" inflicts="40" skill_type="ATTACK_SIMPLE" />
	<skill_template skill_id="965" name="Healing Light I" level="1" launch_time="2" recharge_time="1" heals="93" skill_type="HEAL_SIMPLE" />
	<skill_template skill_id="1099" name="Root I" level="1" launch_time="1"  recharge_time="1" />
	<skill_template skill_id="564" name="Swift Edge I" level="1" launch_time="0" recharge_time="7" inflicts="63" skill_type="ATTACK_SIMPLE" />
	<skill_template skill_id="169" name="Ferocious Strike I" level="1" launch_time="0" recharge_time="10" inflicts="41" skill_type="ATTACK_SIMPLE" />
	<skill_template skill_id="1362" name="Ice Chain I" level="3" element="WATER" launch_time="2"  recharge_time="10" cost="43" inflicts="76" skill_type="SPELL_SIMPLE" />
	<skill_template skill_id="1366" name="Blaze I" level="5" element="FIRE" launch_time="0"  recharge_time="30" cost="62" inflicts="106" skill_type="SPELL_SIMPLE" />
	<skill_template skill_id="1358" name="Erosion I" level="5" element="EARTH" launch_time="0"  recharge_time="3" cost="38" inflicts="34" skill_type="SPELL_SIMPLE" />
	<skill_template skill_id="1355" name="Frozen Shock I" level="7" element="WATER" launch_time="0"  recharge_time="30" cost="52" inflicts="116" skill_type="SPELL_SIMPLE" />
</skill_data>
